/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class AddContactToListByEmails extends SpeakeasyBase {
    /**
     * Emails to add to a list. You can pass a **maximum of 150 emails** for addition in one request. **_If you need to add the emails in bulk, please prefer /contacts/import api._**
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "emails" })
    emails?: string[];
}
