/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class CreateDomainModelDnsRecordsBrevoCode extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "host_name" })
    hostName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}

export class CreateDomainModelDnsRecordsDkimRecord extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "host_name" })
    hostName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}

export class CreateDomainModelDnsRecords extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "brevo_code" })
    @Type(() => CreateDomainModelDnsRecordsBrevoCode)
    brevoCode?: CreateDomainModelDnsRecordsBrevoCode;

    @SpeakeasyMetadata()
    @Expose({ name: "dkim_record" })
    @Type(() => CreateDomainModelDnsRecordsDkimRecord)
    dkimRecord?: CreateDomainModelDnsRecordsDkimRecord;
}

export class CreateDomainModel extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "dns_records" })
    @Type(() => CreateDomainModelDnsRecords)
    dnsRecords?: CreateDomainModelDnsRecords;

    /**
     * Domain
     */
    @SpeakeasyMetadata()
    @Expose({ name: "domain_name" })
    domainName?: string;

    /**
     * ID of the Domain created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    /**
     * Success message
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}
