/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Filter the history for a specific event type
 */
export enum ExportWebhooksHistoryEvent {
    InvalidParameter = "invalid_parameter",
    MissingParameter = "missing_parameter",
    HardBounce = "hardBounce",
    SoftBounce = "softBounce",
    Delivered = "delivered",
    Spam = "spam",
    Request = "request",
    Opened = "opened",
    Click = "click",
    Invalid = "invalid",
    Deferred = "deferred",
    Blocked = "blocked",
    Unsubscribed = "unsubscribed",
    Error = "error",
    UniqueOpened = "uniqueOpened",
    LoadedByProxy = "loadedByProxy",
    AllEvents = "allEvents",
}

export class ExportWebhooksHistory extends SpeakeasyBase {
    /**
     * Number of days in the past including today (positive integer). _Not compatible with 'startDate' and 'endDate'_
     */
    @SpeakeasyMetadata()
    @Expose({ name: "days" })
    days?: number;

    /**
     * Filter the history for a specific email
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * Mandatory if startDate is used. Ending date of the report (YYYY-MM-DD). Must be greater than equal to startDate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "endDate" })
    endDate?: string;

    /**
     * Filter the history for a specific event type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "event" })
    event: ExportWebhooksHistoryEvent;

    /**
     * Filter the history for a specific message id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "messageId" })
    messageId?: number;

    /**
     * Webhook URL to receive CSV file link
     */
    @SpeakeasyMetadata()
    @Expose({ name: "notifyURL" })
    notifyURL: string;

    /**
     * Sorting order of records (asc or desc)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sort" })
    sort?: string;

    /**
     * Mandatory if endDate is used. Starting date of the history (YYYY-MM-DD). Must be lower than equal to endDate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "startDate" })
    startDate?: string;

    /**
     * Filter the history for a specific webhook id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "webhookId" })
    webhookId?: number;
}
