/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class GetAccountActivityLogs extends SpeakeasyBase {
    /**
     * Type of activity in the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action: string;

    /**
     * Time of the activity.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "date" })
    date: string;

    /**
     * Browser details of the user who performed the activity.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_agent" })
    userAgent: string;

    /**
     * Email address of the user who performed activity in the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_email" })
    userEmail: string;

    /**
     * IP address of the user who performed activity in the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_ip" })
    userIp: string;
}

export class GetAccountActivity extends SpeakeasyBase {
    /**
     * Get user activity logs
     */
    @SpeakeasyMetadata({ elemType: GetAccountActivityLogs })
    @Expose({ name: "logs" })
    @Type(() => GetAccountActivityLogs)
    logs?: GetAccountActivityLogs[];
}
