/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Filter the recipients based on how they interacted with the campaign
 */
export enum RequestSmsRecipientExportRecipientsType {
    All = "all",
    Delivered = "delivered",
    Answered = "answered",
    SoftBounces = "softBounces",
    HardBounces = "hardBounces",
    Unsubscribed = "unsubscribed",
}

/**
 * Values to send for a recipient export request
 */
export class RequestSmsRecipientExport extends SpeakeasyBase {
    /**
     * URL that will be called once the export process is finished. For reference, https://help.brevo.com/hc/en-us/articles/360007666479
     */
    @SpeakeasyMetadata()
    @Expose({ name: "notifyURL" })
    notifyURL?: string;

    /**
     * Filter the recipients based on how they interacted with the campaign
     */
    @SpeakeasyMetadata()
    @Expose({ name: "recipientsType" })
    recipientsType: RequestSmsRecipientExportRecipientsType;
}
