/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteChildDomainRequest extends SpeakeasyBase {
    /**
     * Either auth key or id of reseller's child
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=childIdentifier" })
    childIdentifier: string;

    /**
     * Pass the existing domain that needs to be deleted
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=domainName" })
    domainName: string;
}

export class DeleteChildDomainResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * bad request
     */
    @SpeakeasyMetadata()
    errorModel?: shared.ErrorModel;
}
