/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class PostCorporateSubAccountResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created sub-account ID
     */
    @SpeakeasyMetadata()
    createSubAccountResponse?: shared.CreateSubAccountResponse;

    /**
     * Bad request
     */
    @SpeakeasyMetadata()
    errorModel?: shared.ErrorModel;
}
