/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Attributes for company creation
 */
export class PostCompaniesRequestBodyAttributes extends SpeakeasyBase {}

/**
 * Company create data.
 */
export class PostCompaniesRequestBody extends SpeakeasyBase {
    /**
     * Attributes for company creation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "attributes" })
    @Type(() => PostCompaniesRequestBodyAttributes)
    attributes?: PostCompaniesRequestBodyAttributes;

    /**
     * Country code if phone_number is passed in attributes.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "countryCode" })
    countryCode?: number;

    /**
     * Name of company
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}

/**
 * Created company id
 */
export class PostCompanies200ApplicationJSON extends SpeakeasyBase {
    /**
     * Unique company id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

export class PostCompaniesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Returned when invalid data posted
     */
    @SpeakeasyMetadata()
    errorModel?: shared.ErrorModel;

    /**
     * Created new Company
     */
    @SpeakeasyMetadata()
    postCompanies200ApplicationJSONObject?: PostCompanies200ApplicationJSON;
}
