/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class PutCorporateSubAccountIdApplicationsToggleRequest extends SpeakeasyBase {
    /**
     * Id of the sub-account organization (mandatory)
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: number;

    /**
     * List of applications to activate or deactivate on a sub-account
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    subAccountAppsToggleRequest: shared.SubAccountAppsToggleRequest;
}

export class PutCorporateSubAccountIdApplicationsToggleResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * bad request
     */
    @SpeakeasyMetadata()
    errorModel?: shared.ErrorModel;
}
