/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RemoveCreditsRequest extends SpeakeasyBase {
    /**
     * Either auth key or id of reseller's child
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=childIdentifier" })
    childIdentifier: string;

    /**
     * Values to post to remove email or SMS credits from a specific child account
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    removeCredits: shared.RemoveCredits;
}

export class RemoveCreditsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * bad request
     */
    @SpeakeasyMetadata()
    errorModel?: shared.ErrorModel;

    /**
     * Credits removed
     */
    @SpeakeasyMetadata()
    remainingCreditModel?: shared.RemainingCreditModel;
}
