/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateSenderRequest extends SpeakeasyBase {
    /**
     * Id of the sender
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=senderId" })
    senderId: number;

    /**
     * sender's name
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    updateSender?: shared.UpdateSender;
}

export class UpdateSenderResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * bad request
     */
    @SpeakeasyMetadata()
    errorModel?: shared.ErrorModel;
}
