/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type AddCreditsRequest = {
    /**
     * Values to post to add credit to a specific child account
     */
    addCredits: components.AddCredits;
    /**
     * Either auth key or id of reseller's child
     */
    childIdentifier: string;
};

export type AddCreditsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Credits added
     */
    remainingCreditModel?: components.RemainingCreditModel | undefined;
};

/** @internal */
export namespace AddCreditsRequest$ {
    export type Inbound = {
        addCredits: components.AddCredits$.Inbound;
        childIdentifier: string;
    };

    export const inboundSchema: z.ZodType<AddCreditsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            addCredits: z.lazy(() => components.AddCredits$.inboundSchema),
            childIdentifier: z.string(),
        })
        .transform((v) => {
            return {
                addCredits: v.addCredits,
                childIdentifier: v.childIdentifier,
            };
        });

    export type Outbound = {
        addCredits: components.AddCredits$.Outbound;
        childIdentifier: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddCreditsRequest> = z
        .object({
            addCredits: z.lazy(() => components.AddCredits$.outboundSchema),
            childIdentifier: z.string(),
        })
        .transform((v) => {
            return {
                addCredits: v.addCredits,
                childIdentifier: v.childIdentifier,
            };
        });
}

/** @internal */
export namespace AddCreditsResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        remainingCreditModel?: components.RemainingCreditModel$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<AddCreditsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            remainingCreditModel: components.RemainingCreditModel$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.remainingCreditModel === undefined
                    ? null
                    : { remainingCreditModel: v.remainingCreditModel }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        remainingCreditModel?: components.RemainingCreditModel$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddCreditsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            remainingCreditModel: components.RemainingCreditModel$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.remainingCreditModel === undefined
                    ? null
                    : { remainingCreditModel: v.remainingCreditModel }),
            };
        });
}
