/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type DeleteBlockedDomainRequest = {
    /**
     * The name of the domain to be deleted
     */
    domain: string;
};

export type DeleteBlockedDomainResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace DeleteBlockedDomainRequest$ {
    export type Inbound = {
        domain: string;
    };

    export const inboundSchema: z.ZodType<DeleteBlockedDomainRequest, z.ZodTypeDef, Inbound> = z
        .object({
            domain: z.string(),
        })
        .transform((v) => {
            return {
                domain: v.domain,
            };
        });

    export type Outbound = {
        domain: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteBlockedDomainRequest> = z
        .object({
            domain: z.string(),
        })
        .transform((v) => {
            return {
                domain: v.domain,
            };
        });
}

/** @internal */
export namespace DeleteBlockedDomainResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<DeleteBlockedDomainResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteBlockedDomainResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
