/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";

export class GetUserPermissionRequest extends SpeakeasyBase {
    /**
     * Email of the invited user.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=email" })
    email: string;
}

export class GetUserPermissionResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * list of all the user's permissions
     */
    @SpeakeasyMetadata()
    getUserPermission?: components.GetUserPermission;
}
