/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type GetWhatsAppCampaignRequest = {
    /**
     * Id of the campaign
     */
    campaignId: number;
};

export type GetWhatsAppCampaignResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Get WhatsApp campaign information on the basis of campaignId
     */
    getWhatsappCampaignOverview?: components.GetWhatsappCampaignOverview | undefined;
};

/** @internal */
export namespace GetWhatsAppCampaignRequest$ {
    export type Inbound = {
        campaignId: number;
    };

    export const inboundSchema: z.ZodType<GetWhatsAppCampaignRequest, z.ZodTypeDef, Inbound> = z
        .object({
            campaignId: z.number().int(),
        })
        .transform((v) => {
            return {
                campaignId: v.campaignId,
            };
        });

    export type Outbound = {
        campaignId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetWhatsAppCampaignRequest> = z
        .object({
            campaignId: z.number().int(),
        })
        .transform((v) => {
            return {
                campaignId: v.campaignId,
            };
        });
}

/** @internal */
export namespace GetWhatsAppCampaignResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        getWhatsappCampaignOverview?: components.GetWhatsappCampaignOverview$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetWhatsAppCampaignResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            getWhatsappCampaignOverview:
                components.GetWhatsappCampaignOverview$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.getWhatsappCampaignOverview === undefined
                    ? null
                    : { getWhatsappCampaignOverview: v.getWhatsappCampaignOverview }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        getWhatsappCampaignOverview?: components.GetWhatsappCampaignOverview$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetWhatsAppCampaignResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            getWhatsappCampaignOverview:
                components.GetWhatsappCampaignOverview$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.getWhatsappCampaignOverview === undefined
                    ? null
                    : { getWhatsappCampaignOverview: v.getWhatsappCampaignOverview }),
            };
        });
}
