/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type GetWebhookRequest = {
    /**
     * Id of the webhook
     */
    webhookId: number;
};

export type GetWebhookResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Webhook informations
     */
    getWebhook?: components.GetWebhook | undefined;
};

/** @internal */
export namespace GetWebhookRequest$ {
    export type Inbound = {
        webhookId: number;
    };

    export const inboundSchema: z.ZodType<GetWebhookRequest, z.ZodTypeDef, Inbound> = z
        .object({
            webhookId: z.number().int(),
        })
        .transform((v) => {
            return {
                webhookId: v.webhookId,
            };
        });

    export type Outbound = {
        webhookId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetWebhookRequest> = z
        .object({
            webhookId: z.number().int(),
        })
        .transform((v) => {
            return {
                webhookId: v.webhookId,
            };
        });
}

/** @internal */
export namespace GetWebhookResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        getWebhook?: components.GetWebhook$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetWebhookResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            getWebhook: z.lazy(() => components.GetWebhook$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.getWebhook === undefined ? null : { getWebhook: v.getWebhook }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        getWebhook?: components.GetWebhook$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetWebhookResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            getWebhook: z.lazy(() => components.GetWebhook$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.getWebhook === undefined ? null : { getWebhook: v.getWebhook }),
            };
        });
}
