/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Percentage of a particular event for both versions
 */
export class AbTestVersionStats extends SpeakeasyBase {
    /**
     * percentage of an event for version A
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Version A" })
    versionA: string;

    /**
     * percentage of an event for version B
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Version B" })
    versionB: string;
}
