/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateProductModel = {
    /**
     * ID of the Product when a new product is created
     */
    id?: number | undefined;
};

/** @internal */
export namespace CreateProductModel$ {
    export type Inbound = {
        id?: number | undefined;
    };

    export const inboundSchema: z.ZodType<CreateProductModel, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
            };
        });

    export type Outbound = {
        id?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateProductModel> = z
        .object({
            id: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
            };
        });
}
