/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type CreatedProcessId = {
    /**
     * Id of the process created
     */
    processId: number;
};

/** @internal */
export namespace CreatedProcessId$ {
    export type Inbound = {
        processId: number;
    };

    export const inboundSchema: z.ZodType<CreatedProcessId, z.ZodTypeDef, Inbound> = z
        .object({
            processId: z.number().int(),
        })
        .transform((v) => {
            return {
                processId: v.processId,
            };
        });

    export type Outbound = {
        processId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreatedProcessId> = z
        .object({
            processId: z.number().int(),
        })
        .transform((v) => {
            return {
                processId: v.processId,
            };
        });
}
