/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Type } from "class-transformer";

export class GetDomainConfigurationModelBrevoCode extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "host_name" })
    hostName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}

export class GetDomainConfigurationModelDkimRecord extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "host_name" })
    hostName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}

export class GetDomainConfigurationModelDnsRecords extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "brevo_code" })
    @Type(() => GetDomainConfigurationModelBrevoCode)
    brevoCode?: GetDomainConfigurationModelBrevoCode;

    @SpeakeasyMetadata()
    @Expose({ name: "dkim_record" })
    @Type(() => GetDomainConfigurationModelDkimRecord)
    dkimRecord?: GetDomainConfigurationModelDkimRecord;
}

export class GetDomainConfigurationModel extends SpeakeasyBase {
    /**
     * Status of domain authentication (true=authenticated, false=non authenticated)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "authenticated" })
    authenticated: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "dns_records" })
    @Type(() => GetDomainConfigurationModelDnsRecords)
    dnsRecords: GetDomainConfigurationModelDnsRecords;

    /**
     * Domain
     */
    @SpeakeasyMetadata()
    @Expose({ name: "domain" })
    domain: string;

    /**
     * Status of domain verification (true=verified, false=non verified)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "verified" })
    verified: boolean;
}
