/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Type } from "class-transformer";

export class Folders extends SpeakeasyBase {
    /**
     * ID of the folder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    /**
     * Name of the folder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Number of blacklisted contacts in the folder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalBlacklisted" })
    totalBlacklisted: number;

    /**
     * Number of contacts in the folder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalSubscribers" })
    totalSubscribers: number;

    /**
     * Number of unique contacts in the folder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "uniqueSubscribers" })
    uniqueSubscribers: number;
}

export class GetFolders extends SpeakeasyBase {
    /**
     * Number of folders available in your account
     */
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata({ elemType: Folders })
    @Expose({ name: "folders" })
    @Type(() => Folders)
    folders?: Folders[];
}
