/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Task types details
 */
export class TaskTypes extends SpeakeasyBase {
    /**
     * Id of task type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Title of task type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;
}
